### ISSUE TITLE
get_geometry fail for Etc/GMT+12

### ISSUE THREAD

**Issue by Dollars** [jannikmi/timezonefinder#111]
Hi,

First let me say that this package is really nice and useful to me. Thanks a lot.

While I was trying to find the polygons of all the time zones in the `timezone_names` list, I got an error with Etc/GMT+12.
I think it is easily reproducible. I'm using python3.7 with the version 5.1.0 of this package.

```python
>>> from timezonefinder import TimezoneFinder
>>> tf = TimezoneFinder()
>>> tf.get_geometry(tz_name="Etc/GMT+12")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dollars/.virtualenvs/coldrun/lib/python3.6/site-packages/timezonefinder/timezonefinder.py", line 287, in get_geometry
    last_polygon_nr = unpack(DTYPE_FORMAT_H, poly_nr2zone_id.read(NR_BYTES_H))[0]
struct.error: unpack requires a buffer of 2 bytes

unpack requires a buffer of 2 bytes
```

To fix this issue, I propose the change in the PR #110.

**Comment by jannikmi** [comment]
Thanks a lot for your input. It should be fixed in `v5.1.1`. Please try it out and do not hesitate to reopen this issue if errors occur. Greetings
