### ISSUE TITLE
Won't install on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by wo1fmane** [jannikmi/timezonefinder#114]
I'm trying to make a car "computer" with a Raspberry Pi Zero W and a Pimoroni Micro Dot Phat to replace the defunct one in my Mercury. I plan on using a GPSr module and temperature and humidity sensor to make it completely offline and not have to connect anything to the car itself other than power. Anyway, I'm having problems getting this to install.

When I run the command:
>pip install timezonefinder[numba]
or
>pip install timezonefinder

it gets to 99%, then sits for a while, then eventually exits, printing "Killed"

This is the output:
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting timezonefinder
  Downloading https://files.pythonhosted.org/packages/3c/a1/544681d5a58cd0a80ac914d81f983cdd3a07d4791789a29f26e329033e3c/timezonefinder-4.2.0.tar.gz (38.1MB)
    99% |############################### | 38.1MB 1.9MB/s eta 0:00:01Killed

If I try this command:
>sudo pip install timezonefinder --no-cache-dir

Then this is the output:
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting timezonefinder
  Downloading https://files.pythonhosted.org/packages/3c/a1/544681d5a58cd0a80ac914d81f983cdd3a07d4791789a29f26e329033e3c/timezonefinder-4.2.0.tar.gz (38.1MB)
    100% |################################| 38.1MB 1.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ihBxtk/timezonefinder/setup.py", line 7, in <module>
        from timezonefinder.global_settings import DATA_FILE_NAMES
      File "timezonefinder/__init__.py", line 2, in <module>
        from .timezonefinder import TimezoneFinder
      File "timezonefinder/timezonefinder.py", line 276
        def closest_timezone_at(self, *, lat, lng, delta_degree=1, exact_computation=False, return_distances=False,
                                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ihBxtk/timezonefinder/

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

So I'm assuming that the Pi runs out of memory in the first case, but with the second one I'm thinking it may be an incompatibility with Python 3 vs. 2.7? I'm not sure where to go with this.

I already have online weather API working and the NTP will set the clock, but both require Internet and I would like everything to work when I'm out in the boonies and have no mobile service. It would also be nice to have the clock change time zones automatically. I do frequent long-distance multi-state trips, and it's a hassle to have to keep resetting the clock.

Any help getting this working would be greatly appreciated.

**Comment by jannikmi** [comment]
Thanks for reporting this. Are you running these commands within an environment with python2? If so, please try with python3 and report if the error persists.

**Comment by wo1fmane** [comment]
Argh! Newbie mistake. I knew Python 3.8 was installed, but I wrongly assumed the environment would default to that. 2.7 is also installed, and that was what I was using. Replacing the command line with:

>sudo pip3 install timezonefinder[numba]

got much further, even without "--no-cache-dir".

Now I'm getting dependency errors related to "llvm-config". I'm working on resolving that now.

Thanks!

**Comment by wo1fmane** [comment]
Apparently there's something different about Raspberry Pi OS that treats llvm differently. After much searching and modifying commands did this:

>sudo apt install llvm-9
>sudo LLVM_CONFIG=llvm-config-9 pip3 install llvmlite

It resolved all the remaining issues (with the install, anyway... I still have some debugging to do with my Python LOL). However, the developers of numba say that may not always work because they use a custome version of llvm. (Thanks a lot!)

Thanks for your quick response and for providing this package!

**Comment by jannikmi** [comment]
Glad I could help. Thanks for posting your resolution. From what you write about your use case, I think it is not worth it for you to run `timezonefidner` with Numba. If you are running just a couple of queries, the benefit does not outweigh the increased resource requirements of Numba/llvm. Please consider staring this repository if you like it. Thanks.
