### ISSUE TITLE
Difficulty with v5 API for evaluating likelihood of results

### ISSUE THREAD

**Issue by NickFabry** [jannikmi/timezonefinder#118]
Hello! First, thank you for contributing this project to the world; it has saved me countless hours (well, I actually did count them once, it was 50+ before I found this project) in determining timezones for my work.

However, with the transition to the v5 API, where the certain_timezone_at() function has been deprecated and the ocean timezones included, I can no longer effectively use the closest_timezone_at() function, since I never wish to consider the oceanic timezones since they are never valid for the objects I am looking up.

My specific project is mapping International Air Transport Association [IATA] three character airport codes (e.g. "EWR" for Newark Liberty International Airport in Newark, NJ, USA; not "KEWR", which is the ICAO code for the airport) to IANA time zones (e.g. "America/New_York"). I start from a table of IATA airport codes and their lat-long coordinates, among other information, and using your library to associate each unqiue IATA code with a unique IANA time zone. Since there are 8822 IATA airports, this would be extremely difficult to do manually.

A sample of what the output looks like:

```csv
airport_uid	name	near_city	country	state	lat_ns	lat_deg	lat_min	lat_dd	lng_ew	lng_deg	lng_min	lng_dd	country_tz	no_dst	tz	tz_quality

EWO	Ewo	False	CG		S	0	51	-0.85	E	14	48	14.8	CG	False	Africa/Brazzaville	1
EWR	Newark Liberty Intl	True	US	NJ	N	40	41	40.68333333333333	W	74	10	-74.16666666666667	US1	False	America/New_York	1
EXI	Excursion Inlet	False	US	AK	N	58	25	58.416666666666664	W	135	26	-135.43333333333334	US5	False	America/Juneau	1
HAP	Whitsunday Is	False	AU	QL	S	19	10	-19.166666666666668	E	147	40	147.66666666666666	AU2	False	Australia/Brisbane	2
HYN	Huangyan	False	CN		N	28	25	28.416666666666668	E	122	22	122.36666666666666	CN	False	Asia/Shanghai	2
JAT	Jabat	False	MH		N	7	0	7.0	E	168	59	168.98333333333332	MH1	False	Pacific/Majuro	3
SOH	Solita	False	CO		N	34	14	34.233333333333334	W	71	45	-71.75	CO	False		3
```

Note the field, tz_quality. This field was an indicator of how likely it was that the tz output was correct. It was generated by the following code, relying on the v4 API:

```python
# v4 API
r['tz'] = tf.certain_timezone_at(lat=r['lat_dd'], lng=r['lng_dd'])
r['tz_quality'] = 1
if not r['tz']:
    r['tz'] = tf.timezone_at(lat=r['lat_dd'], lng=r['lng_dd'])
    r['tz_quality'] = 2
if not r['tz']:
    r['tz'] = tf.closest_timezone_at(lat=r['lat_dd'], lng=r['lng_dd'])
    r['tz_quality'] = 3
if not r['tz']:
    print(f"No tz found for {r['airport_uid']}: {r['name']} @\
                   {r['lat_dd']}, {r['lng_dd']}")
final_list.append(r)
```

In english; if the airport was *definitely* in a timezone (certain_timezone_at() returns a result), the tz_quality was 1. If the exact match failed, try the fast but less precise function, timezone_at() - if that worked, the tz_quality was 2. If that failed, try the closest_timezone_at() function to return a best guess, and the tz_quality was 3.

The idea was hopefully, most or all of the airports would would be tz_quality 1. The few airports that were tz_quality 2 or 3 could be manually researched, but hopefully the IANA time zones determined for them would be correct.

This idea worked very well in practice; of the 8822 airports, only 18 airports were tz_quality 2, and all of the guessed zones turned out to be correct; only 9 airports were tz_quality 3, and of those, six zones were guessed correctly, and only three were blank and had to be manually determined.

However, with the new v5 API, there is no equivalent way to determine likelyhood of an airport being within a certain timezone. The problem is the new oceanic timezones mean that every function (other than timezone_at_land()) can return an oceanic timezone. The closest I could make my code function with the v5 API is with the following:

```python
	# v5 API
        r['tz'] = tf.timezone_at_land(lat=r['lat_dd'],
                                      lng=r['lng_dd'])
        r['tz_quality'] = 1
        if not r['tz']:
            r['tz'] = tf.unique_timezone_at(lat=r['lat_dd'],
                                            lng=r['lng_dd'])
            r['tz_quality'] = 2
        if not r['tz']:
            r['tz'] = tf.timezone_at(lat=r['lat_dd'],
                                     lng=r['lng_dd'])
            r['tz_quality'] = 3
        if not r['tz']:
            r['tz'] = tf.closest_timezone_at(lat=r['lat_dd'],
                                             lng=r['lng_dd'])
            r['tz_quality'] = 4
        if not r['tz']:
            print(f"No tz found for {r['airport_uid']}: {r['name']} @\
                   {r['lat_dd']}, {r['lng_dd']}")
        final_list.append(r)
```

Now I get about two dozen airports mapped to oceanic timezones, which I know are incorrect, and have to be manually fixed; a sample of the new output requiring a manual fix is below:

```csv
airport_uid	name	near_city	country	state	lat_ns	lat_deg	lat_min	lat_dd	lng_ew	lng_deg	lng_min	lng_dd	country_tz	no_dst	tz	tz_quality
APK	Apataki	False	PF		S	15	5	-15.083333333333334	W	145	20	-145.33333333333334	PF2	False	Etc/GMT+10	3
BCZ	Bickerton Is	False	AU	NT	S	13	47	-13.783333333333333	E	137	48	137.8	AU3	False	Etc/GMT-9	3
CQP	Cape Flattery	False	AU	QL	S	18	12	-18.2	E	147	30	147.5	AU2	False	Etc/GMT-10	3
HAP	Whitsunday Is	False	AU	QL	S	19	10	-19.166666666666668	E	147	40	147.66666666666666	AU2	False	Etc/GMT-10	3
HYN	Huangyan	False	CN		N	28	25	28.416666666666668	E	122	22	122.36666666666666	CN	False	Etc/GMT-8	3
JAT	Jabat	False	MH		N	7	0	7.0	E	168	59	168.98333333333332	MH1	False	Etc/GMT-11	2
```

I don't know any obvious way to fix this with the current v5 API. Correctness of result is far more important to me than speed of execution, as this only has to be run whenever a new IANA timezone database is published (a few times a year), or IATA updates it's airport code list (approximately every quarter year.)

Do you have any ideas? Perhaps I'm missing something?

Thanks for your thoughts on this.

**Comment by jannikmi** [comment]
Hello Nick, thanks for your positive feedback. Quite an interesting use case and solution you have there! Glad this package helps.

You could parse the data without oceans yourself: https://timezonefinder.readthedocs.io/en/latest/2_use_cases.html#data-parsing-shell-script
Since the closest_timezone_at() functionality has not changed (is just meaningless to use with ocean data) you can use it as before v5.
Let me know if that resolved your issue.

More specifically it would be nice to know if your insights could be used to improve timezonefinder or the boundary data: https://github.com/evansiroky/timezone-boundary-builder
Can your reproduce the reason for timezones not being matched correctly?
Is that always the case for the same set of airports? Could you correct their coordinates in order to improve the (automatic) results?

**Comment by NickFabry** [comment]
Thank you for the suggestion above; that prompted me to read the documentation a little more closely, and realized I could get a list of nearest timezones and then manually filter it to exclude those with Etc/ and sort to find the closest one like so:

```python
        r['tz'] = tf.timezone_at_land(lat=r['lat_dd'], lng=r['lng_dd'])
        r['tz_quality'] = 1
        # Note that not getting a land timezone for an airport is most
        # usually caused by an erroneous lat-long. The TimezoneFinder
        # and associated shape files are pretty damned good.
        if not r['tz']:
            tz_data = tf.closest_timezone_at(lat=r['lat_dd'],
                lng=r['lng_dd'], exact_computation=True,
                return_distances=True, force_evaluation=True)
            print(f"WARNING: Uncertain timezone for {r['airport_uid']}:"
                  f" {tz_data}")
            possible_zones =\
                [(dist, zone) for dist, zone in zip(tz_data[1], tz_data[2])
                              if zone[0:3] != 'Etc']
            possible_zones.sort(key=lambda x: x[0])
            if possible_zones:
                print(f'Choosing {possible_zones[0][1]} with smallest '
                      f'distance of {possible_zones[0][0]}')
                r['tz'] = possible_zones[0][1]
                r['tz_quality'] = 2
            else:
                print(f"ERROR: No tz found for {r['airport_uid']}: "
                      f"{r['name']} @ {r['lat_dd']}, {r['lng_dd']}")
        final_list.append(r)
```

Excerpt of output with the above code:
```
WARNING: Uncertain timezone for SQP: ('Etc/GMT-10', array([166.54344195]), ['Etc/GMT-10'])
ERROR: No tz found for SQP: Starcke @ -14.2, 147.16666666666666
WARNING: Uncertain timezone for SSB: ('America/St_Thomas', array([104.78102738, 112.50430172, 181.53100027, 180.30501022,
       178.22970391, 193.98338152, 146.23383587, 181.56338489,
       247.86597796, 303.62888619, 103.80819426,  41.58830312,
       279.10008059, 234.61411194, 103.80819426, 212.10395901,
       191.74590288]), ['America/Puerto_Rico', 'America/Tortola', 'America/Anguilla', 'America/Lower_Princes', 'America/Marigot', 'America/St_Barthelemy', 'America/Kralendijk', 'America/St_Kitts', 'America/Montserrat', 'America/Guadeloupe', 'America/St_Thomas', 'America/St_Thomas', 'America/Antigua', 'America/Antigua', 'Etc/GMT+4', 'Etc/GMT+4', 'Etc/GMT+4'])
Choosing America/St_Thomas with smallest distance of 41.58830312070208
WARNING: Uncertain timezone for TIH: ('Pacific/Tahiti', array([354.16992695, 121.30853244,  40.02418233,  31.08191535,
        47.69391122, 114.21405098]), ['Etc/GMT+10', 'Etc/GMT+10', 'Pacific/Tahiti', 'Pacific/Tahiti', 'Pacific/Tahiti', 'Pacific/Tahiti'])
Choosing Pacific/Tahiti with smallest distance of 31.08191534890197
```


I then planned to document the 28 or so airports which reported oceanic timezones for the sake of timezonefinder/timezone-boundary-builder... and after a few hours of research, discovered that *every one* had an erroneous latitude and/or longitude! Most of the errors were a few dozen minutes to a degree off, but that was plenty to place those airports in the oceans...

Once I corrected the lat-longs for the 28 airports, the timezone was found correctly by timezone_at_land() for every one. So, there is nothing to correct here!

Thanks very much for your suggestions - they put me on the right track. If you're ever curious about the project I'm working on, feel free to ping me.

(And now I have to submit the corrected lat-longs to the source of the airport data...)
