### ISSUE TITLE
Having trouble with .timezone_at()

### ISSUE THREAD

**Issue by antonplkv** [jannikmi/timezonefinder#120]
I have a cron task running in celery and calling .timezone_at(), and inside this method there is exception on line

```
 _getattr(self, SHORTCUTS_UNIQUE_ID).seek(
            (NR_LAT_SHORTCUTS * NR_BYTES_H * shortcut_id_x + NR_BYTES_H * shortcut_id_y)_
```

such like

_OSError timezonefinder.timezonefinder in timezone_at
[Errno 9] Bad file descriptor_

What is the possible problem?
Should i provide requirements and stack trace?

Thanks.

**Comment by jannikmi** [comment]
Thanks for reporting this. Can you reproduce this exact error and point of failure on every function call or is the error only from time to time?
Yes any traceback and environment info could be helpful.

**Comment by antonplkv** [comment]
Thanks for your reply.

It`s mostly regular thing because it ocurse when celery cron task starts . I can not reproduce it by myself and only have sentry logs which points to this. 

Created gist with function calls and requirements. 
OS used - Ubuntu 18.04

https://gist.github.com/antonplkv/bb7886161877e9db38278324ba718731

**Comment by jannikmi** [comment]
I am guessing that there is some kind of incompatibility between your runtime environment (OS permissions etc.) and the binary files `timezonefinder` wants to open/use. Perhaps you can check if just opening a file, like timezonefinder does, works in your celery setup.
Whats weird is that I cannot find the line you reference
`getattr(self, SHORTCUTS_UNIQUE_ID).seek(...` anywhere in the code.
