### ISSUE TITLE
Wrong returned timezone

### ISSUE THREAD

**Issue by cnpante12** [jannikmi/timezonefinder#121]
Hi I upgraded timezonefinder from 4.3.1 to 5.2.0. In the last version I looked for the timezone using the specific coordinates describe in the code below. It returned `None`. So I upgraded to 5.2.0, then the return becomes `GMT-8`. The timezone for that coordinates should be `GMT+8`.
```
from timezonefinder import TimezoneFinder

center_lon = 117.68520010023614
center_lat = 10.891010631283473

def timezone_from_loc(lat, lon):
    tf = TimezoneFinder()
    return tf.timezone_at(lng=lon, lat=lat)


timezone = timezone_from_loc(center_lat, center_lon)
print(timezone) # GMT-8
```

I have also tried making the `center_lon` negative i.e. `-117.68520010023614`, then the returned timezone becomes `GMT+8`, which should be the opposite.

**Comment by jannikmi** [comment]
That is indeed weird. Lets see what the Mr. Siroky has to say.

btw. i would highly recommend writing:

``` python
tf = TimezoneFinder()
def timezone_from_loc(lat, lon):
    return tf.timezone_at(lng=lon, lat=lat)
```

That is far more performant when you query multiple timezones.

**Comment by cnpante12** [comment]
Thank you @jannikmi!

**Comment by jannikmi** [comment]
Ok, this is actually intended behavior! Look at the answer in the other issue. Still thanks for reporting this. I did not know about it either.
