### ISSUE TITLE
Problem with timezone_at()

### ISSUE THREAD

**Issue by mpv1953** [jannikmi/timezonefinder#122]
I have installed timezonefinder (5.2.0) on a Raspberry Pi Zero running the latest edition of Raspbian and Python 3.7.3.
root@piznc03:/etc# pip3 freeze | grep -i time
timezonefinder==5.2.0
root@piznc03:/etc# uname -a
Linux piznc03 5.10.17+ #1421 Thu May 27 13:58:02 BST 2021 armv6l GNU/Linux
root@piznc03:/etc#
This code:
pi@piznc03:~/projects/daynight $ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from timezonefinder import TimezoneFinder
tf = TimezoneFinder()
TimezoneFinder.using_numba()
>>> tf = TimezoneFinder()
>>> TimezoneFinder.using_numba()
True
>>> lat=float( 33.5800 )
>>> lon=float( -117.2057 )
>>> tf.timezone_at(lng=lon, lat=lat)
'Etc/GMT+12'
>>>

Should return 'America/Los_Angeles'.
root@piznc03:/etc# timedatectl
               Local time: Thu 2021-06-24 19:08:01 PDT
           Universal time: Fri 2021-06-25 02:08:01 UTC
                 RTC time: n/a
                Time zone: America/Los_Angeles (PDT, -0700)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
root@piznc03:/etc#

Thanks for looking.
- Mike
-

**Comment by jannikmi** [comment]
Thanks for reporting this. That is really strange, since I cannot replicate this:
https://timezonefinder.michelfe.it/gui/0_-117.2057_33.5800

Do you get any erroneous values for other time zones back as well?

**Comment by mpv1953** [comment]
Hello!  Thank you for responding.  I'm starting to think it's a configuration issue of some kind, because every different lat/long combination I have tried reports the same thing.
[tztest.txt](https://github.com/jannikmi/timezonefinder/files/6717887/tztest.txt)
I have attached a text file created with "script" on the Pi.
- Mike

**Comment by mpv1953** [comment]
Hello Again!
I will close this issue.  The problem was being caused by the installation of "numba".  TimezoneFinder is now reporting the correct information.
Thanks Again!
- Mike
(Hmmm... can't upload a second file.  This is a paste from the file...)

root@piznc03:~#
root@piznc03:~# pip3 uninstall numba
Uninstalling numba-0.53.1:
  Would remove:
    /usr/local/bin/numba
    /usr/local/bin/pycc
    /usr/local/lib/python3.7/dist-packages/numba-0.53.1.dist-info/*
    /usr/local/lib/python3.7/dist-packages/numba/*
Proceed (y/n)? y
  Successfully uninstalled numba-0.53.1
root@piznc03:~#




pi@piznc03:~/projects/daynight $ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from timezonefinder import TimezoneFinder
>>> TimezoneFinder.using_numba()
False
>>>
>>> tf = TimezoneFinder()
>>> latitude = float( 33.5800 )
>>> longitude = float( -117.2057 )
>>> tf.timezone_at( lng=longitude, lat=latitude )
'America/Los_Angeles'
>>> latitude = float( 34.49152 )
>>> longitude = float( -114.35778 )
>>> tf.timezone_at( lng=longitude, lat=latitude )
'America/Phoenix'
>>> latitude = float( 42.5708 )
>>> longitude = float( -88.5562 )
>>> tf.timezone_at( lng=longitude, lat=latitude )
'America/Chicago'
>>> latitude = float( 38.9212 )
>>> longitude = float( -77.0665 )
>>> tf.timezone_at( lng=longitude, lat=latitude )
'America/New_York'
>>>
pi@piznc03:~/projects/daynight $

**Comment by mpv1953** [comment]
Thank you!

**Comment by jannikmi** [comment]
Oh, that is strange. That should actually not happen and tests with numba being installed actually run fine. In case you find out more about the issue causing this behavior, please report back here. Thank you!
