### ISSUE TITLE
.at_timezone Does not work for Antarctica latitudes and longitudes.

### ISSUE THREAD

**Issue by jaredsjordan** [jannikmi/timezonefinder#123]
tf.at_timezone(lat=-75.098, lng = 123.35) gives "Australia/Perth" Or Australian Western Standard Time (GMT +8)
When it should give "Antarctica/Casey" Or New Zealand Standard Time (GMT +12)

**Comment by jannikmi** [comment]
Thank you for pointing that out. I reposted this here: https://github.com/evansiroky/timezone-boundary-builder/issues/104
That actually might be intended behavior. Timezones are not intuitive in many cases and I think geopolitically Antarctica is an especially difficuly region.

**Comment by jannikmi** [comment]
This behavior is actually intended: https://en.wikipedia.org/wiki/Time_in_Antarctica

**Comment by evansiroky** [comment]
@jaredsjordan, as noted in the timezone-boundary-builder project, most of the boundaries for Antarctica timezones are a best guess by myself. If you have supporting evidence for possible changes to the boundary, I would be happy to facilitate any needed corrections in the timezone-boundary-builder project.
