### ISSUE TITLE
.timezone_at() capable of receiving utc time in addition to coordinates

### ISSUE THREAD

**Issue by martindevora** [jannikmi/timezonefinder#124]
Hi,

I was wondering whether it'd be possible to include a third parameter to .timezone_at method so that a timezone can be obtained for latitude, longitude and a utc or julian date time. I'm proposing this because I'd be interested into knowing the timezone for a random place and time in the near future, where the timezone is subject to seasonal variations (like winter and summer times).

Regards.

**Comment by jannikmi** [comment]
sure:
https://timezonefinder.readthedocs.io/en/latest/2_use_cases.html#getting-a-location-s-time-zone-offset
