### ISSUE TITLE
Add function to look up country for given coordinates

### ISSUE THREAD

**Issue by kdebrab** [jannikmi/timezonefinder#126]
Thanks for creating and maintaining this package! It's useful and working really well.

I have a feature request, which is not really in the scope of this package, but still very useful as it fills a gap: I didn't find anything comparable to this package to look up a country for given coordinates. See e.g. https://stackoverflow.com/questions/1425149/reverse-geocoding-without-web-access, https://stackoverflow.com/questions/20169467/how-to-convert-from-longitude-and-latitude-to-country-or-city.

I guess the data inside this package could also be used to look up the country for given coordinates. E.g. when you get 'Europe/Paris' as timezone, it means the country is 'France'.

If really out of the scope, it would be nice to have data shared with another package, e.g. countryfinder, such that data duplication is avoided.

**Comment by jannikmi** [comment]
Thank you for this feature request. Actually, yes the implementation should be fairly straight forward as long as there is a map from the [timezone names](https://github.com/jannikmi/timezonefinder/blob/master/timezonefinder/timezone_names.json) to a country name.

Would you consider providing an initial JSON dictionary for this?
I can then take care of the rest easily

**Comment by jannikmi** [comment]
As an idea to speed this up I would consider writing a little script for scraping and then parsing https://en.wikipedia.org/wiki/List_of_national_capitals
There will be some cases which have to be hard coded for sure, but that shouldn't be a problem.

**Comment by jannikmi** [comment]
I have looked at the discussions you have linked and this package seems to offer the functionality you are looking for:
https://github.com/thampiman/reverse-geocoder
Or am I missing something?

**Comment by jannikmi** [comment]
I am closing this issue now. Feel free to reopen this if you have further input on this
