### ISSUE TITLE
Django's Decimal not being accepted as input value

### ISSUE THREAD

**Issue by rez0n** [jannikmi/timezonefinder#130]
Hi, I am faced with the strange issue that is a common way to store lng&lat in Django it is a Decimal field, but it isn't accepted by your package.
```
TypeError: No matching definition for argument type(s) pyobject, pyobject
```
Casting value to the float helps to deal with that, but maybe worth to accept Decimal?

**Comment by jannikmi** [comment]
Thanks for the suggestion. Do you have a suggestion how to achieve this without introducing Django as a dependency?

**Comment by jannikmi** [comment]
I am closing this now. Feel free to reopen this issue if you have ideas for this.
