### ISSUE TITLE
The timezonefinder sdist requires luck to use.

### ISSUE THREAD

**Issue by jsirois** [jannikmi/timezonefinder#132]
This is due to `setup.py` indirectly depending on numpy. At the 5.2.0 tag where I observed the issue this is via:
https://github.com/jannikmi/timezonefinder/blob/d7f616210021739bfaa3cbcf59e46c6c6b18f85a/setup.py#L4
https://github.com/jannikmi/timezonefinder/blob/d7f616210021739bfaa3cbcf59e46c6c6b18f85a/timezonefinder/__init__.py#L2
https://github.com/jannikmi/timezonefinder/blob/d7f616210021739bfaa3cbcf59e46c6c6b18f85a/timezonefinder/timezonefinder.py#L11

So, although there is a runtime dependency on numpy expressed via `install_requires`:
https://github.com/jannikmi/timezonefinder/blob/d7f616210021739bfaa3cbcf59e46c6c6b18f85a/setup.py#L41

There is no corresponding `setup_requires` - which is the best you can do with `setup.py` (but it tends not to work well which I'm guessing you all know already).

There appears to be awareness of this issue in the repo's publish script here:
https://github.com/jannikmi/timezonefinder/blob/477963f3e7069f4c6ec68b4841e0462f8d08c28c/publish.py#L2-L3

Unfortunately, those instructions don't help automated build tools like Pip; i.e.: You have to manually make sure numpy is installed in a venv before installing timezonefinder.

This should be fixable for both your internal publish script and end users of the sdist by using the new poetry build setup that is on master and [`poetry publish`](https://python-poetry.org/docs/cli/#publish) after migrating the distribution metadata out of `setup.py` and into `pyproject.toml`. From my scan of your `setup.py` it looks like there are no exotic features used and all configuration has a direct corresponding configuration item supported by Poetry.

**Comment by jsirois** [comment]
I'll take a crack at this change with a PR in case you're interested in doing things that way. I may find out though that its not so simple! We shall see.

**Comment by jsirois** [comment]
Aha, setup.py has been fixed on master to not import from the project and thus indirectly require numpy. It looks like the next published sdist should not have this bug! Sorry for the noise.

**Comment by jannikmi** [comment]
Thanks for bringing this up. There will be a release soon. Please reopen this issue if required.
