### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by unk2k** [jannikmi/timezonefinder#142]
Hi, we have used your library and it looks awesome, thanks you all.

As an example, we will use this code:
```
from timezonefinder import TimezoneFinder
from random import randint
for i in range(1000):
 tf = TimezoneFinder()
 tf.timezone_at(lat=randint(20,40), lng=randint(30,60))
```

On version 5.2.0 it takes 0.01 second
On version 6.0.1 and higher it takes 20 or more seconds.

Could you please explain to me, what I did wrong?
Thanks!

**Comment by jannikmi** [comment]
Thank you for pointing this out.
What makes your example slow is that you initialise the `tf = TimezoneFinder()` instance within the loop (1000 times).
This should be done only once as this includes some slow initialization steps.
Here is an updated example:

``` python
from random import randint
from timeit import timeit

from timezonefinder import TimezoneFinder

N = 1000
tf = TimezoneFinder()


def experiment():
    for i in range(N):
        lat = float(randint(20, 40))
        lng = float(randint(30, 60))
        _ = tf.timezone_at(lat=lat, lng=lng)


print(f"testing {N} points")
t = timeit("experiment()",globals=globals(),  number=1)
print(f"took {t}s")

pts_p_sec = int(N / t)
print(f"avg. points per second: {pts_p_sec:}")
```
which gives me

```
testing 1000 points
took 0.10970432099999994s
avg. points per second: 9115
```

If you want this to be faster and it's ok to use more Memory, use:
```python
tf = TimezoneFinder(in_memory=True)
```
->

```
testing 1000 points
took 0.032036879999999934s
avg. points per second: 31214
```

Hope that helps.

**Comment by jannikmi** [comment]
Even more importantly if you care about speed you should install `Numba`:
```
pip install timezonefinder[numba]
```
https://timezonefinder.readthedocs.io/en/latest/3_about.html#speed-test-results
