### ISSUE TITLE
Performance on polygon’s edge is slow

### ISSUE THREAD

**Issue by ringsaturn** [jannikmi/timezonefinder#146]
I found that even toggle numba, lookup near edge is much slower than center.

```
pytest
pytest-benchmark
timezonefinder[numba]==6.0.2
```

```py
from timezonefinder import TimezoneFinder

f = TimezoneFinder(in_memory=True)

f.timezone_at(lng=-0.17578125, lat=51.7814356044311)
f.timezone_at(lng=-5.033111572265626, lat=49.79988210788039)


def test_center(benchmark):
    benchmark.pedantic(
        f.timezone_at, kwargs={"lng": -0.17578125, "lat": 51.7814356044311}
    )


def test_edge(benchmark):
    benchmark.pedantic(
        f.timezone_at, kwargs={"lng": -5.033111572265626, "lat": 49.79988210788039}
    )
```

```
------------------------------------------------------------------------------------- benchmark: 2 tests -------------------------------------------------------------------------------------
Name (time in us)          Min                 Max                Mean            StdDev              Median               IQR            Outliers  OPS (Kops/s)            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_center            29.0490 (1.0)       29.0490 (1.0)       29.0490 (1.0)      0.0000 (1.0)       29.0490 (1.0)      0.0000 (1.0)           0;0       34.4246 (1.0)           1           1
test_edge             121.8710 (4.20)     121.8710 (4.20)     121.8710 (4.20)     0.0000 (1.0)      121.8710 (4.20)     0.0000 (1.0)           0;0        8.2054 (0.24)          1           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
================================================================================= 2 passed in 0.74s ==================================================================================
```

**Comment by jannikmi** [comment]
Indeed, but this is a feature not a bug. 

In the "center" of a timezone polygon there might be only one possible timezone stored in the index. Hence this zone will be directly returned without performing a point in polygon test. 

On the edge (bordering another polygon from a different zone) a point in polygon test needs to be performed.

Does that make sense?

**Comment by jannikmi** [comment]
Please let me know if there are any doubts.

**Comment by ringsaturn** [comment]
I made another package named [tzfpy](https://github.com/ringsaturn/tzf/tree/main/python) which only use a simple point-in-polygon search in Go, and performance is basically stable, and the std/max is much smaller than timezonefinder.

Maybe the point-in-polygon search algorithm implementation in timezonefinder have some performance	issue around the edge?

CI sample: https://github.com/ringsaturn/tz-benchmark/runs/7609973126?check_suite_focus=true#step:6:75

**Comment by jannikmi** [comment]
The variance of speed is probably not due to the point in polygon algorithm, but the indexing (using the h3 library) which allows skipping the point in polygons tests completely when no other zone possible. 

The use of a faster point in polygon algorithm implementation however would be a good improvement of this package. Does the lack of speed prevent you from using timezonefinder? If so, I am motivated to fix this with your help.

**Comment by ringsaturn** [comment]
If the fastet query came with indexing, it's reasonable for me.

How should I run a benchmark when the timezonefinder's indexing is disabled?

---

For background:

In our production, timezonefider without Numba is deployed to serve at least 10K queries per second, and some edge queries could be up to 2s and slow the system. We have decied to toggle Numba when we are ready to solve the problem.

I want to know whether timezonefinder with Numba could be as stable as possible, becuase in the benchmark I provided the std is a little large.

**Comment by jannikmi** [comment]
Ok I see. I guess this huge variance is actually then due to Numba just in time compiling the functions for the first time. All consequent runs should then be much faster.


Try using the function .certain_timezone_at() for always performing the point in polygon test (still using indexing but preventing to return one zone without checking for inclusion).

Using a faster and more stable point in polygon algorithm implementation is then a good option. Do you think the golang choice you mentioned is preferable?

**Comment by ringsaturn** [comment]
Thanks, we will try Numba to see if there any slow query in production.

Use Golang in Python is not a good choise. Releasd wheels will be compiled to multi platforms if with data bundled the all files sizes will reach PyPI's limit. You can see tzfpy's release [here](https://pypi.org/project/tzfpy/#files).

In my benchmark, the current implementation is fast enough, only the unknown slow queries worries me.

I have add multi round test cases which is clear that after JIT the std is pretty stable. CI sample here <https://github.com/ringsaturn/tz-benchmark/runs/7664495556?check_suite_focus=true#step:6:88>

**Comment by jannikmi** [comment]
Ok, let me know if you think something could be done to improve this package.

**Comment by jannikmi** [comment]
@ringsaturn  please check the new release 6.1.0 and see if it works (fast enough) for you even without Numba installed. I have now included a C extension for the point in polygon check algorithms which should get compiled automatically during the build.

**Comment by ringsaturn** [comment]
Impressive performance improvements event without Numba!

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/13536789/185726911-d799e5b5-683d-4d54-abf6-a53beb2341f5.png">

https://ringsaturn.github.io/tz-benchmark/

**Comment by jannikmi** [comment]
Glad to hear that. It seems as if the C extension have been compiles successfully.
