### ISSUE TITLE
pip installation is broken

### ISSUE THREAD

**Issue by G-Tarik** [jannikmi/timezonefinder#151]
After version 6.0.1 the `pip install timezonefinder` creates files and folders from  timezonefinder repository and `site-packages` looks like this:
```
    venv/bin/timezonefinder
    venv/lib/python3.8/site-packages/.editorconfig
    venv/lib/python3.8/site-packages/.pre-commit-config.yaml
    venv/lib/python3.8/site-packages/CHANGELOG.rst
    venv/lib/python3.8/site-packages/CONTRIBUTING.rst
    venv/lib/python3.8/site-packages/LICENSE
    venv/lib/python3.8/site-packages/Makefile
    venv/lib/python3.8/site-packages/README.rst
    venv/lib/python3.8/site-packages/inside_poly_extension/inside_polygon_int.c
    venv/lib/python3.8/site-packages/inside_poly_extension/inside_polygon_int.h
    venv/lib/python3.8/site-packages/parse_data.sh
    venv/lib/python3.8/site-packages/scripts/*
    venv/lib/python3.8/site-packages/tests/*
    venv/lib/python3.8/site-packages/timezonefinder-6.1.0.dist-info/*
    venv/lib/python3.8/site-packages/timezonefinder/*
    venv/lib/python3.8/site-packages/tox.ini

```
This breaks other imports. For example I have a folder `scripts` and my command `from scripts.my_module import my_object` does not work anymore.   
**Expected behavior:** everything is installed under folder `venv/lib/python3.8/site-packages/timezonefinder/`

**Comment by jannikmi** [comment]
Thanks for reporting this. 
It seems like that is how poetry based packaging works. I will check how to change that behavior.

**Comment by jannikmi** [comment]
I have found no standardized way to change this behavior. In case someone knows about this please post here. 
I have read that it is considered good practice to include tests etc. in a distribution for devs to run locally in case something is broken.

For now however, I simply reduced the distribution footprint in the latest release `6.1.1` (excluded all those additional files and folders) please check if it solves your issue.

Different topic:
To know whether the compilation/import of the new C extension worked in your case, could you please run this:

``` python
from timezonefinder import TimezoneFinder
print(f"using Numba: {TimezoneFinder.using_numba()}")
print(f"using C ext: {TimezoneFinder.using_clang_pip()}")
```

**Comment by G-Tarik** [comment]
@jannikmi, thank you for quick fix! It solved issue in my case. 

Here is output for commands which you requested:
![image](https://user-images.githubusercontent.com/22340709/185435195-007dea2e-b838-4d01-95ca-d4a327b3693f.png)

In case it helps you, here is a list of installed dependencies:
![image](https://user-images.githubusercontent.com/22340709/185435913-211d2460-847a-4335-84b6-9132659615f5.png)

**Comment by jannikmi** [comment]
Ok, too bad. 
Do you know if you have a C compiler installed?
Please have in mind that with this setup `timezonefinder` can be quite slow.
Make sure to install `Numba` or a C compiler if speed is an issue for you. Thx

**Comment by Friptick** [comment]
Hello @jannikmi. This looks related. Upgrading Ubuntu to the latest LTS has caused the `timezonefinder` dependency in my project to break. Now, doing `pip install timezonefinder` raises the following error:
```
  Building wheels for collected packages: timezonefinder
  Building wheel for timezonefinder (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for timezonefinder (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-install-en24mbez/timezonefinder_65d8d582436b9481927ca119527c6ecd/build.py", line 35, in <module>
          ffibuilder = FFI()
        File "/tmp/pip-build-env-sndbc62f/overlay/local/lib/python3.10/dist-packages/cffi/api.py", line 54, in __init__
          raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
      Exception: Version mismatch: this is the 'cffi' package version 1.15.1, located in '/tmp/pip-build-env-sndbc62f/overlay/local/lib/python3.10/dist-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.15.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
      Traceback (most recent call last):
        File "/home/jc/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/jc/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jc/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-sndbc62f/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/api.py", line 67, in build_wheel
          return WheelBuilder.make_in(poetry, Path(wheel_directory))
        File "/tmp/pip-build-env-sndbc62f/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/wheel.py", line 79, in make_in
          wb.build(target_dir=directory)
        File "/tmp/pip-build-env-sndbc62f/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/wheel.py", line 109, in build
          self._build(zip_file)
        File "/tmp/pip-build-env-sndbc62f/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/wheel.py", line 157, in _build
          self._run_build_script(self._package.build_script)
        File "/tmp/pip-build-env-sndbc62f/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/wheel.py", line 217, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python3', 'build.py']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for timezonefinder
Failed to build timezonefinder
ERROR: Could not build wheels for timezonefinder, which is required to install pyproject.toml-based projects
```
I am not a PIP expert (except in the fact that I know it breaks annoyingly often).

I have done a `python3 -m pip install -q --upgrade pip` and `sudo apt install python-wheel-common`. Same error.

Python version is 3.10.4. Pip version is 22.2.2.

Is there a quick fix here?

**Comment by jannikmi** [comment]
Not sure how this can happen, but its about two different versions of the `cffi` dependency:
```
'cffi' package version 1.15.1, located in '/tmp/pip-build-env-sndbc62f/overlay/local/lib/python3.10/dist-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.15.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
```
Please make sure to use the same version in both places.

**Comment by Friptick** [comment]
Thanks. So I have tried uninstalling `cffi`, reinstalling `cffi`, purging `cffi`, every which way imaginable. Doing `pip install cffi==1.15.0`. Flushing every cache I can find. Running commands with `--no-cache-dir` and redownloading every dependency. Still getting same error. Very frustrating. If you know an obvious fix, step by step, that would be helpful. If not, no problem, I'll get there eventually.

**Comment by jannikmi** [comment]
I am creating a new release with a bugfix for this. I will let you know once its available

**Comment by jannikmi** [comment]
@Friptick, please try again with version `6.1.2`

**Comment by Friptick** [comment]
@jannikmi Thanks.
```
$ pip install timezonefinder --no-cache-dir
Defaulting to user installation because normal site-packages is not writeable
Collecting timezonefinder
  Downloading timezonefinder-6.1.2.tar.gz (45.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 MB 2.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting h3<4.0.0,>=3.7.3
  Downloading h3-3.7.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.4 MB/s eta 0:00:00
Collecting cffi<2.0.0,>=1.15.1
  Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 kB 2.9 MB/s eta 0:00:00
Collecting numpy<2.0,>=1.22
  Downloading numpy-1.23.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 2.0 MB/s eta 0:00:00
Collecting setuptools<66.0.0,>=65.3.0
  Downloading setuptools-65.3.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.1 MB/s eta 0:00:00
Requirement already satisfied: pycparser in ./.local/lib/python3.10/site-packages (from cffi<2.0.0,>=1.15.1->timezonefinder) (2.21)
Building wheels for collected packages: timezonefinder
  Building wheel for timezonefinder (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for timezonefinder (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
```
Followed by the exact same trace as above! :( Exasperating.

**Comment by Friptick** [comment]
Update. Tried this:
```
$ pip install cffi==1.15.1
Defaulting to user installation because normal site-packages is not writeable
Collecting cffi==1.15.1
  Using cached cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
Requirement already satisfied: pycparser in ./.local/lib/python3.10/site-packages (from cffi==1.15.1) (2.21)
Installing collected packages: cffi
  Attempting uninstall: cffi
    Found existing installation: cffi 1.15.0
    Uninstalling cffi-1.15.0:
      Successfully uninstalled cffi-1.15.0
Successfully installed cffi-1.15.1
```
Looked promising! But same error on trying to install `timezonefinder`

About that pseudo-error `normal site-packages is not writeable`, from research I understand that it's basically a warning rather than an error. I have no need to install system packages if user-scoping is the default. And using virtual environments seems like overkill for a small handful of single-user standalone Python scripts.

Anyway, I can cheerfully announce that I have run out of ideas again. Thanks for any more you may have.

**Comment by jannikmi** [comment]
If you hit dependency incompatibilities like these, I think using a virtual environment is the most promising and straight forward approach. Apart from that I also don't have any obvious other ideas.

**Comment by Friptick** [comment]
Well, you obviously know what you are talking about so I trust that advice.

But to have to maintain a virtual environment with its own directory is kinda dumb. I'm not maintaining separate projects, I'm not working across systems or in collaboration. I just want the output of a single Python script, called from a single shell script. I thought `pip` was a Python dependency manager. Well, I want it to take care of my Python dependencies, and apparently it can't. By contrast, in 15 years as an ordinary dumb user I have never had a problem like this with `apt`, which just works. None of this is your fault, I'm sure, please forgive the rant.

I just replaced the `timezonefinder` requirement from my script with `tzwhere`. Seems to work. I understand that your project is more advanced, but I would like to keep things as simple as possible.

Thanks for the tips and for taking the time to help.

**Comment by jannikmi** [comment]
Thanks for reporting this.

One last idea: please try to uninstall `cffi` before installing timezonefinder: `pip uninstall cffi`
do you need it for some other package?

**Comment by Friptick** [comment]
Tried that already, see above. Just tried again, with `--no-cache-dir` to be sure. Installing timezonefinder pulls in `cffi` 1.15.1, as expected.

Then... Same error on building wheel. All exactly the same unfortunately.
