### ISSUE TITLE
Incorrect Timezone "America/Nipigon" returned for location in Milton CA.

### ISSUE THREAD

**Issue by shivaRamdeen** [jannikmi/timezonefinder#157]
lat=43.522788
lng=-79.859662

location_at(lat=lat, lng=lng) 

returns "America/Nipigon" timezone. older versions of timezonefinder returned "America/Toronto" we are upgrading to the latest version of timezone finder and these differences have failed unit tests.

Old version=4.1.0
New version: tested 5.2.0 to 6.1.3

Any Insight is greatly appreciated.

**Comment by jannikmi** [comment]
How do you know this new result is incorrect?
I don't know about the reasoning behind the timezone separation in toronto, but there seems to be a timezone boundary within toronto: https://timezonefinder.michelfe.it/gui/0_-79.859662_43.522788
Let me know if you find any error in the new results.

**Comment by shivaRamdeen** [comment]
https://timezonedb.com/ You can use this site to see the differences compared to what this library gives as a result.

In addition, if you look at the polygons they seem to have holes where there shouldn't.

I am no timezone expert but a GPS location in Milton should be america/toronto.

**Comment by jannikmi** [comment]
This issue deals with the same or similar topic, please have a look: https://github.com/evansiroky/timezone-boundary-builder/issues/131
FYI: [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder) is the timezone data source being used by timezonefinder.
In my experience timezones can be quite messy.

**Comment by shivaRamdeen** [comment]
@jannikmi thanks, I'll take a look, once the issue is patched in timezone-boundary-builder will this package also need a patch?

**Comment by jannikmi** [comment]
For every new release of the boundary data I will release a new version.
