### ISSUE TITLE
Extreme slowness, no log about CFFI build failing

### ISSUE THREAD

**Issue by antoineleclair** [jannikmi/timezonefinder#159]
We recently updated from version 6.0.2 to 6.1.1 (and we also tried 6.1.2), and the library is very slow now. We downgraded to 6.0.2 for now, because it was unusable for us.

Our app runs on Heroku. I had a look at the logs of both builds when deploying, and there's no mention of anything failing for timezonefinder.

After looking in the code here, I see it probably fails silently.
https://github.com/jannikmi/timezonefinder/blob/5dc365ccdd21509e0ea16b5e400b81838ac8c592/build.py#L64-L70

At the moment, I don't know of a way for us to debug further.

Running this on 6.1.1 returns `True`
```python
from timezonefinder import TimezoneFinder
TimezoneFinder.using_clang_pip()
```
But it's still super slow anyway.

So I think the main issue is that there's no info about the build failure being logged. And also, it used to work, but now it fails for some reason, so there's probably something that could be fixed.

Let me know if I can provide more info.

**Comment by jannikmi** [comment]
Thanks for reporting this. Please double check shortly that you are reusing the same `TimezoneFinder` instance for multiple calls:
``` python
from timezonefinder import TimezoneFinder

tf = TimezoneFinder()  # reuse

query_points = [(13.358, 52.5061), ...]
for lng, lat in query_points:
    tz = tf.timezone_at(lng=lng, lat=lat)  # 'Europe/Berlin'
```

Then as an alternative please try installing the optional numba dependency with `pip install timezonefinder[numba]`.

Let me know if that improves the performance.

**Comment by antoineleclair** [comment]
Thank you for the super quick reply. We'll try this and get back to you.

**Comment by antoineleclair** [comment]
Yes!

Re-using it totally fixed the issue!

We probably got away with it in the past, but now it's much slower to instanciate it for every call.

Thank you so much for assisting with this.
