### ISSUE TITLE
Updates to timezonefinder[numba]

### ISSUE THREAD

**Issue by m4rcelofs** [jannikmi/timezonefinder#162]
Hello there!

Timezonefinder [declares](https://github.com/jannikmi/timezonefinder/blob/master/pyproject.toml#L37) numba as an optional dependency using `^0.55.2` and numba itself requires `numpy<1.23`. For reference, numba is now on `0.56.3` and numpy on `1.23.4` (which will not be installed because of the caret declaration).

This makes it impossible for anyone using the latest numpy as a dependency to require `timezonefinder[numba]`; could the dependency be updated to something more permissive eg. `>=0.55.2`? I'm happy to open a PR if that's preferred.

The workaround is to just require both `timezonefinder==6.1.3` and `numba==0.56.3` directly, but this makes the requirements file harder to understand if you have no other uses for numba.

**Comment by jannikmi** [comment]
Thanks for reporting this. Yes, please open a PR.
