### ISSUE TITLE
lat lon format?

### ISSUE THREAD

**Issue by alainlhostis** [jannikmi/timezonefinder#173]
I seem to have troubles using 'timezone_at' with the current latitude and longitudes I have in myb CSV:
`"001.50.33W","50.46.48N"`

Should I transform those coordinates into decimal values?

**Comment by jannikmi** [comment]
Yes, exactly.

**Comment by jannikmi** [comment]
@alainlhostis as the solution might be relevant for other users as well, can you please post the code for converting the coordinates into floating point numbers here. I will add it to the documentation then as reference. Thanks
