### ISSUE TITLE
TimezoneFinder() spend a long time with M1 cpu

### ISSUE THREAD

**Issue by liuxindtc** [jannikmi/timezonefinder#176]
environment:python 3.10 / timezonefinder-5.2.0

* code

```
from timezonefinder import TimezoneFinder

number = 100
for i in range(number):
    TimezoneFinder()
```

* result
```
intel mac: 0.067s
M1 mac:28.46s [amazing!!!]
```

Is there something wrong with me?
BTW, TimezoneFinder of `timezonefinderL` works fine on M1 and intel.

**Comment by jannikmi** [comment]
Please reuse the Timezonefinder instance for multiple timezone queries.
