### ISSUE TITLE
CI/CD: Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by jannikmi** [jannikmi/timezonefinder#195]
test steps
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, pre-commit/action@v2.0.3, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by Mourishitz** [comment]
Hello @jannikmi!!

I have just submited a Pull Request with the node version changes, you can check it here https://github.com/jannikmi/timezonefinder/pull/200

Hope this solves the problem, and if not, I'd be pleasured to hear and contribute to your project
