### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by Gui-FernandesBR** [jannikmi/timezonefinder#208]
Python 3.12 was released a few weeks ago, but so far I could not install `timezonefinder` using pip, as commented here: https://github.com/jannikmi/timezonefinder/issues/207#issuecomment-1784208567

I opened an issue on h3 since this was the error that I got, so I'm currently waiting for their updates: https://github.com/uber/h3-py/issues/326

Any other problems when building on Python 3.12?

**Comment by ringsaturn** [comment]
Numba: https://github.com/numba/numba/issues/9197

**Comment by nhoover** [comment]
I'm also having this problem. Using python 3.12.1. Please fix - thanks!

**Comment by jannikmi** [comment]
@nhoover @Gui-FernandesBR please check if you can install the new release `6.4.0` with python 3.12 and report back if not.

**Comment by nhoover** [comment]
Back in December to work around this I switched to tzfpy but I just tried installing timezonefinder 6.4.0 and got:

Successfully built timezonefinder Failed to build h3 error: subprocess-exited-with-error Building wheel for h3 (pyproject.toml) did not run successfully. exit code: 1 [356 lines of output]

**Comment by ringsaturn** [comment]
> Back in December to work around this I switched to tzfpy but I just tried installing timezonefinder 6.4.0 and got:
> 
> Successfully built timezonefinder Failed to build h3 error: subprocess-exited-with-error Building wheel for h3 (pyproject.toml) did not run successfully. exit code: 1 [356 lines of output]

I believe it's related to #207, as it came from here: https://github.com/uber/h3-py/issues/326

However I can install timezonefinder 6.4.0 under 3.12, see https://github.com/ringsaturn/tz-benchmark/pull/143

Maybe you can provide more details info to h3-py repo.
