### ISSUE TITLE
Can't install `timezonefinder` with numpy 2.0

### ISSUE THREAD

**Issue by Gui-FernandesBR** [jannikmi/timezonefinder#234]
Hello,

numpy 2.0.0 was officially released today (https://pypi.org/project/numpy/)
However, the `pyproject.toml` file states numpy<2.0 as a dependency for timezonefinder.
I have successfully executed all the tests from the `tests` folder after updating numpy to 2.0.
It seems like this project doesn't really requires numpy <2.

Can we flexibilize the rules in the pyproject.toml file so timezonefinder can be installed with numpy 2.0? 

There's a migration guide for numpy 2.0. The Python API changes are minimum:
- https://numpy.org/devdocs/numpy_2_0_migration_guide.html

**Comment by Gui-FernandesBR** [comment]
@jannikmi if you need help I could open up a PR solving this issue.

As far as I understand, no modifications to the code source would be needed.

**Comment by jannikmi** [comment]
Thanks for bringing this up. Yes, please open a PR.

**Comment by jannikmi** [comment]
I am on it.
