### ISSUE TITLE
Problem in Greek waters: Aegean 

### ISSUE THREAD

**Issue by Wikinaut** [jannikmi/timezonefinder#242]
![grafik](https://github.com/user-attachments/assets/f436c52a-013c-4823-8cec-a7322721a4fa)

![grafik](https://github.com/user-attachments/assets/6b93045a-d0bd-416c-a871-d538a5844d72)

Please can you have look to this issue. The timezone should be for both EEST (at the moment, summer).

**Comment by jannikmi** [comment]
Thanks for reporting this. Could you please specify which code should output what, according to your expectations? Please note that "EEST" is not a supported return value.

**Comment by jannikmi** [comment]
I am closing this now due to inactivity. Please reply if this is still relevant
