### ISSUE TITLE
cannot get timezone based on specific point in time (daylight saving time)

### ISSUE THREAD

**Issue by hhp-the-maestro** [jannikmi/timezonefinder#246]
Problem Statement:
Always returns the timezone based on the latitude and longitude irrespective of the time. globally many regions are subject to daylight saving at specific time intervals and its hard to get the timezone at a particular point of time may be in future.

**Comment by jannikmi** [comment]
Thanks for bringing this up. Perhaps this helps: https://timezonefinder.readthedocs.io/en/latest/2_use_cases.html#getting-a-location-s-time-zone-offset
