### ISSUE TITLE
Performance degraded by 8x

### ISSUE THREAD

**Issue by jvacek** [jannikmi/timezonefinder#253]
Between 6.5.2 and 6.5.3 we noticed an ~800% increase in time taken to complete the same loop.

After profiling, it seems most of the time goes to `pt_in_poly_python`.

Let me know if there's any other info you need to help troubleshoot this.

**Comment by jvacek** [comment]
Looks like with 6.5.2 we were using the clang version, not sure why we'd be switching to the python one but it's coming from here

https://github.com/jannikmi/timezonefinder/commit/437113ffb4c1ce007fd24dada7b6a6ec3ac15db8#diff-004ace7ca04755ff5d00d7eeb3045b910a59d9a6af99c7ecd7af0acd53297d65R143-R148

**Comment by jannikmi** [comment]
Thanks for bringing this up. Unfortunately I don't have the capacity to look into this. Can anyone help out? 

The tests (CI/CD) should be expanded to test both the C implementation and without (similar to the Numba alternative).

As a temporary workaround you could try enabling the Numba implementation or downgrading for a Speedup.

**Comment by jvacek** [comment]
Thanks for the prompt reply, we'll downgrade for the time being.

> try enabling the Numba implementation

Is there documentation for this?

**Comment by jannikmi** [comment]
@jvacek could you please test if you can locally import and use the c lang helpers (see the respective python module and tests).

**Comment by jvacek** [comment]
On 6.5.3,
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/ba1eaf06-ed01-4e37-8740-a44d3d93c9dd">

**Comment by jannikmi** [comment]
For documentation, please check:

https://timezonefinder.readthedocs.io/en/latest/7_performance.html#numba

**Comment by jannikmi** [comment]
Could you please run the tests of this package (Pytest) locally? These includes running the clang version of the point in polygon implementation.

**Comment by jannikmi** [comment]
Could you please navigate to the directory where `timezonefinder` is installed and run `pytest`.

What is the value of `timezonefinder.utils_clang.clang_extension_loaded`?

**Comment by jannikmi** [comment]
I noticed that the tests are failing because the C extension is not being loaded when I run the tests locally on MacOS: https://github.com/jannikmi/timezonefinder/issues/255

**Comment by jvacek** [comment]
Will run the pytest later, but FYI this also happened in a cronjob on our k8s cluster, which is running python 3.10.3 on _I think_ a buster-slim image

**Comment by jannikmi** [comment]
Could you please try again with the latest version `6.5.4`. Thank you

**Comment by jvacek** [comment]
6.5.4 works well, and it's using clang again. thanks for the super fast fix! Cheers
