### ISSUE TITLE
Provide musllinux wheel

### ISSUE THREAD

**Issue by sanmai-NL** [jannikmi/timezonefinder#259]
To support Linux containers based on Alpine Linux.

**Comment by jannikmi** [comment]
@sanmai-NL thanks for bringing this up.
Can anyone help with this?

**Comment by Pxli9130** [comment]
@jannikmi @sanmai-NL I’m interested in contributing to this project by working on this issue to provide musllinux wheel support. Could you assign this issue to me? I’ll give it a try.

**Comment by sanmai-NL** [comment]
@jannikmi can @Pxli9130

**Comment by jannikmi** [comment]
@Pxli9130 done. Thanks
